# Generated by Django 4.2.7 on 2023-12-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_km',
            field=models.IntegerField(default=1),
        ),
    ]
