# Generated by Django 4.2.7 on 2024-02-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_carwashrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='carwashrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='carwashrequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.driver'),
        ),
        migrations.AddField(
            model_name='carwashrequest',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle'),
        ),
        migrations.AlterField(
            model_name='carwashrequest',
            name='service_type',
            field=models.CharField(max_length=100),
        ),
    ]
