# Generated by Django 4.2.7 on 2024-02-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_carwashrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashrequest',
            name='vehicle',
        ),
    ]
