# Generated by Django 4.2.7 on 2024-02-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_carwashrequest_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_type', models.CharField(choices=[('puncture', 'Puncture'), ('change', 'Change'), ('alignment', 'Alignment')], max_length=20)),
                ('date_needed', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.driver')),
            ],
        ),
    ]
