# Generated by Django 4.2.7 on 2024-02-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_engineservicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('a/c repair', 'A/C Repair'), ('sound system', 'Sound System')], max_length=20)),
                ('date_needed', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.driver')),
            ],
        ),
    ]
