# Generated by Django 4.2.7 on 2024-02-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_interiorservicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineservicerequest',
            name='approvalStatus',
            field=models.BooleanField(default=False),
        ),
    ]
