# Generated by Django 4.2.7 on 2024-02-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_engineservicerequest_approvalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashrequest',
            name='approvalStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interiorservicerequest',
            name='approvalStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tyreupgraderequest',
            name='approvalStatus',
            field=models.BooleanField(default=False),
        ),
    ]
